### ISSUE TITLE
Additional Standard Operators

### ISSUE THREAD

**Issue by Shinmera** [Shinmera/for#1]
The following operators have been suggested and should be added as they seem generally useful:
- <s>Sequencing binding. This would allow combining multiple bindings into a single one, by which each successive binding is applied to the var after the current one were to call end-loop. I believe this can be achieved by either locally shadowing the end-for macro or rewriting it in source to something that would switch the currently active iteration body binding to the next operator.</s>
- <s>Conditional binding updating. For the simplest case, finding a certain value, we'd like to only update the var if a predicate test succeeds. This can be further generalised to allow arbitrary bindings that only update conditionally as would be useful for accumulation clauses and so forth.</s>
- Foreign updating binding. Only update to a certain value if a different binding updates its var. This would allow something like a "finding" operator based on max, min, etc.

**Comment by mfiano** [comment]
Good work here. A few additional enhancements:

- Feature request to add the only thing I came here looking for that is lacking from LOOP: binding multiple values like list destructuring.

- Make note in the docs that the generic `over` iterator is much slower than using a specific one.

- It would be easier to understand the docs if there were LOOP versions of the examples.

**Comment by Shinmera** [comment]
How would destructuring multiple values work? The only thing that comes to my mind right now is to allow something like a `:key` parameter to each iteration construct to which you can pass something like `multiple-value-list`.

**Comment by mfiano** [comment]
In thinking about it, this is not easily implemented, nor does it make much sense (the values thing).
