### ISSUE TITLE
Destructuring support for =

### ISSUE THREAD

**Issue by hackeryarn** [Shinmera/for#8]
I have a case where I am trying to destructure a value using `=`. I would expect this to work, but I seem to get an error of the second variable being unbound.

A simplified case of this is:

```
(for:for (((x y) = '(1 2)))
  (print x)
  (print y))
```

When I execute this code, I get `The variable Y is unbound.`

Also, thank you so much for this macro! I really love the semantics of it and think it makes things much clearer and more consistent that `loop` or `iterate`.

**Comment by Shinmera** [comment]
Glad to have a (mostly) satisfied customer :)
